variable:
    blog: ./template
    theme: ${blog}/theme

task:
    default:
        - ${#build_theme}
        - ${build_ink}
    build_theme:
        - cd ${theme} && webpack
    build_ink:
        - "go fmt && go build"
        - "./ink preview ${blog}"
    release:
        - rsync -av template/* blog --exclude public --exclude theme/node_modules
        - $GOPATH/bin/goxc -d=release -bc="linux windows darwin" -include=blog
        - rm -r blog
        - mv release/snapshot/ink_windows_amd64.zip ../ink-web/release/.
        - mv release/snapshot/ink_windows_386.zip ../ink-web/release/.
        - mv release/snapshot/ink_darwin_amd64.zip ../ink-web/release/.
        - mv release/snapshot/ink_linux_amd64.tar.gz ../ink-web/release/.
        - mv release/snapshot/ink_linux_386.tar.gz ../ink-web/release/.

watch:
    ./*.go: ${build_ink}
    ${theme}/source/css/*.less: ${default}
    ${theme}/source/js/*.coffee: ${default}
    ${theme}/*.html: ${default}
