site:
    title: 猫叔の杂记 · 手帐
    subtitle: 代码，美术，音乐与二次元
    logo: -/images/avatar.jpg
    limit: 10
    theme: theme
    disqus: imeoer
    root: /blog
    lang: zh

authors:
    me:
        name: 猫叔
        intro: 程序员，关注设计与二次元
        avatar: -/images/avatar.jpg

build:
    port: 8000
    copy:
        # Copied files to public folder when build
        - theme/css
        - theme/js
        - theme/favicon.ico
        - theme/robots.txt
        - source/images
    publish: |
        # Excuted command when use 'ink publish'
        git add . -A
        git commit -m "update"
        git push origin
